kind: Service
apiVersion: v1
metadata:
  name: db
  labels:
    name: db-service
    app: 'demo-voting-app'
spec:
  selector:
    name: 'postgres-pod'
    pod: 'demo-voting-app'
  type: ClusterIP
  ports:
    - name: postgres-service-port
      targetPort: 5432
      port: 5432
