kind: Service
apiVersion: v1
metadata:
  name: Service Name
  labels:
    name: redis-service
    app: 'demo-voting-app'
spec:
  selector:
    name: 'redis-pod'
    pod: 'demo-voting-app'
  type: ClusterIP
  ports:
    - name: redis-service
      targetPort: 6379
      port: 6379
