apiVersion: v1
kind: Pod
metadata:
  name: 'result-app-pod'
  namespace: default
  labels:
    name: 'result-app-pod'
    pod: 'demo-voting-app'
spec:
  containers:
    - name: result-app-container
      image: kodekloud/examplevotingapp_result:v1
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      ports:
        - containerPort: 80
          name: http
      volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
  volumes:
    - name: localtime
      hostPath:
        path: /usr/share/zoneinfo/Asia/Shanghai
  restartPolicy: Always
