kind: Service
apiVersion: v1
metadata:
  name: result-app
  labels:
    name: result-app-service
    app: 'demo-result-app'
spec:
  selector:
    name: 'result-app-pod'
    pod: 'demo-result-app'
  type: NodePort
  ports:
    - name: result-app-port
      targetPort: 80
      port: 80
      nodePort: 30005
