kind: Service
apiVersion: v1
metadata:
  name: voting-app
  labels:
    name: voting-app-service
    app: 'demo-voting-app'
spec:
  selector:
    name: 'voting-app-pod'
    pod: 'demo-voting-app'
  type: ClusterIP
  ports:
    - name: voting-app-port
      targetPort: 80
      port: 80
